CREATE TABLE MEDS (
	ENTRY_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID INT NOT NULL,
    MED_NAME VARCHAR(255) NOT NULL,
    MOR_DOSE INT,
    AFT_DOSE INT,
    EVE_DOSE INT,
    FOREIGN KEY (ID) REFERENCES PATIENT (ID)
);
